### PR TITLE
Add latex version of the user manual

### PR DESCRIPTION
**Pull request by ptormene**
This PR adds a translation of the user manual into latex. I had to fix the basic structure, the formulas and the cross-references. The bibliography is currently managed as it was in the original text (using footnotes and inline citations, instead of putting everything in a separate bibliography). In the future this might be changed.
The styling is (intentionally) very basic and we will need to wait for a standard style to make this manual homogeneous with the other GEM user manuals.
I am keeping the manual inside the plugin's repository, but I am not 100% sure this is what we want (although it sounds quite reasonable to me).

### CODE REVIEW

**Comment by burtonchrisp** [comment]
I’m asking Vitor to send over theLaTex files used for the risk and hazard manuals. I’ll also send you James's cover page.

**Comment by ptormene** [comment]
Thank you Chris, both will be useful

**Comment by ptormene** [comment]
Missing headers with copyright etc.

**Comment by ptormene** [comment]
We are trying a different approach: https://github.com/gem/oq-irmt-qgis/pull/98

**Pull request closed without merging**
